language: node_js
node_js:
    - "0.10"
script: node_modules/karma/bin/karma start my.conf.js --single-run
before_install:
  
before_script:
    - npm install
cache:
  directories:
    - node_modules
